### ISSUE TITLE
"Challange" with updating an policy by export/import

### ISSUE THREAD

**Issue by moxter** [MxUpdate/Update#98]
_From [bu...@mbudde.com](https://code.google.com/u/117065304958043317945/) on February 09, 2010 03:34:56_

What steps will reproduce the problem? open an mql console and log in as creator
1. prepare test data:
   execute following commands:
   add policy Test type Part state Started state Processing state Stopped;
   add property state_Started on policy Test value Started;
   add property state_Processing on policy Test value Processing;
   add property state_Stopped on policy Test value Stopped;
   add property policy_Test on program eServiceSchemaVariableMapping.tcl to 
   policy Test;
2. assume you have to change the state name on a policy which was not 
   exported yet but is present in the database.
   execute following commands:
   mod policy Test state Processing name Jabbo;
   mod property state_Processing on policy Test value Jabbo;
3. export the policy using MxUpdate
   3.1 execute: exec prog MxUpdate -e --policy Test --path <your export path 
   here>;
4. reset the policy to simulate an not updated environment
   execute following commands:
   mod policy Test state Jabbo name Processing;
   mod property state_Processing on policy Test value Processing;
5. update the policy using MxUpdate
   5.1. open an mql console and log in as creator
   5.2. execute: exec prog MxUpdate -u --policy Test --path <your export path 
   here>; What is the expected output? What do you see instead? expected:
   confirmation of change. The second state should now be named Jabbo and the 
   property with the states symbolic name should be "state_Processing" with 
   value "Jabbo".

what i got:
----------------------- ERROR MSG START -----------------------------
MQL<17>exec prog MxUpdate -u --policy Test --path c:\temp\mxupdate;
check policy 'Test'
    - update
    - insert new state 'Jabbo' before 'Processing'
java.lang.Exception: some states are not defined anymore!
        at 
org.mxupdate.update.datamodel.Policy_mxJPOvwXpjQAAAAEAAAAb.jpoCallExe
cute(Policy_mxJPOvwXpjQAAAAEAAAAb.java:490)
        at org.mxupdate.update.util.JPOCaller_mxJPOC$DnuQAAAAEAAAAQ.mxMain
(JPOCa
ller_mxJPOC$DnuQAAAAEAAAAQ.java:195)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at matrix.db.JPOSupport.invokeObject(JPOSupport.java:125)
        at com.matrixone.jni.MatrixKernel.statelessDispatch(Native Method)
        at com.matrixone.jni.MatrixKernel.doStatelessDispatch
(MatrixKernel.java:
81)
        at com.matrixone.jdl.rmi.bosMQLCommandImpl.executeCmd
(bosMQLCommandImpl.
java:53)
        at matrix.db.MQLCommand.executeCommand(MQLCommand.java:90)
        at org.mxupdate.update.util.MqlUtil_mxJPOC$D0twAAAAEAAAAD.execMql
(MqlUti
l_mxJPOC$D0twAAAAEAAAAD.java:78)
        at org.mxupdate.update.util.MqlUtil_mxJPOC$D0twAAAAEAAAAD.execMql
(MqlUti
l_mxJPOC$D0twAAAAEAAAAD.java:56)
        at 
org.mxupdate.update.AbstractPropertyObject_mxJPOjJoKSwAAAAEAAAAQ.upda
te(AbstractPropertyObject_mxJPOjJoKSwAAAAEAAAAQ.java:551)
        at 
org.mxupdate.update.AbstractAdminObject_mxJPOMQXqtQAAAAEAAAAS.update(
AbstractAdminObject_mxJPOMQXqtQAAAAEAAAAS.java:680)
        at 
org.mxupdate.update.datamodel.AbstractDMWithTriggers_mxJPOUy0gggAAAAE
AAAAT.update(AbstractDMWithTriggers_mxJPOUy0gggAAAAEAAAAT.java:174)
        at 
org.mxupdate.update.datamodel.Policy_mxJPOvwXpjQAAAAEAAAAb.update(Pol
icy_mxJPOvwXpjQAAAAEAAAAb.java:408)
        at 
org.mxupdate.update.AbstractPropertyObject_mxJPOjJoKSwAAAAEAAAAQ.upda
te(AbstractPropertyObject_mxJPOjJoKSwAAAAEAAAAQ.java:384)
        at MxUpdate_mxJPOz701pgAAAAEAAAAP.update
(MxUpdate_mxJPOz701pgAAAAEAAAAP.
java:737)
        at MxUpdate_mxJPOz701pgAAAAEAAAAP.mxMain
(MxUpdate_mxJPOz701pgAAAAEAAAAP.
java:479)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at matrix.db.JPOSupport.invokeObject(JPOSupport.java:125)
Error: #1900068: exec program failed
System Error: #5000001: java.lang.Exception: some states are not defined 
anymore
!

MQL command was:
tcl;
eval  {
set AUTHOR "The MxUpdate Team"
set INSTALLER "The MxUpdate Team"
set NAME "Test"
set VERSION ""
set ORIGINALNAME "Test"
set APPLICATION "Unknown"
set FILEDATE "02-09-2010 10:31:54.314"
set SYMBOLICNAME "policy_Test"
proc updatePolicy {_sPolicy _lsArgs}  {
regsub -all {'} $_lsArgs {@0@0@} sArg
regsub -all {\"} $sArg {@1@1@} sArg
regsub -all {\[} $sArg {[} sArg
regsub -all {\]} $sArg {]} sArg
mql exec prog org.mxupdate.update.util.JPOCaller policy $_sPolicy "${sArg}"
}

source "c:/temp/mxupdate/datamodel/policy/POLICY_Test.tcl"
}
exit;
escape mod policy "Test"  add property "version" value "" add 
property "file dat
e" value "02-09-2010 10:31:54.314";
output '';output 'MxUpdate Executed';

```
    at org.mxupdate.update.util.MqlUtil_mxJPOC$D0twAAAAEAAAAD.execMql
```

(MqlUti
l_mxJPOC$D0twAAAAEAAAAD.java:80)
        at org.mxupdate.update.util.MqlUtil_mxJPOC$D0twAAAAEAAAAD.execMql
(MqlUti
l_mxJPOC$D0twAAAAEAAAAD.java:56)
        at 
org.mxupdate.update.AbstractPropertyObject_mxJPOjJoKSwAAAAEAAAAQ.upda
te(AbstractPropertyObject_mxJPOjJoKSwAAAAEAAAAQ.java:551)
        at 
org.mxupdate.update.AbstractAdminObject_mxJPOMQXqtQAAAAEAAAAS.update(
AbstractAdminObject_mxJPOMQXqtQAAAAEAAAAS.java:680)
        at 
org.mxupdate.update.datamodel.AbstractDMWithTriggers_mxJPOUy0gggAAAAE
AAAAT.update(AbstractDMWithTriggers_mxJPOUy0gggAAAAEAAAAT.java:174)
        at 
org.mxupdate.update.datamodel.Policy_mxJPOvwXpjQAAAAEAAAAb.update(Pol
icy_mxJPOvwXpjQAAAAEAAAAb.java:408)
        at 
org.mxupdate.update.AbstractPropertyObject_mxJPOjJoKSwAAAAEAAAAQ.upda
te(AbstractPropertyObject_mxJPOjJoKSwAAAAEAAAAQ.java:384)
        at MxUpdate_mxJPOz701pgAAAAEAAAAP.update
(MxUpdate_mxJPOz701pgAAAAEAAAAP.
java:737)
        at MxUpdate_mxJPOz701pgAAAAEAAAAP.mxMain
(MxUpdate_mxJPOz701pgAAAAEAAAAP.
java:479)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at matrix.db.JPOSupport.invokeObject(JPOSupport.java:125)
Error: #1900068: exec program failed
System Error: #5000001: Error: #1900068: exec program failed
System Error: #5000001: java.lang.Exception: some states are not defined 
anymore
!

MQL command was:
tcl;
eval  {
set AUTHOR "The MxUpdate Team"
set INSTALLER "The MxUpdate Team"
set NAME "Test"
set VERSION ""
set ORIGINALNAME "Test"
set APPLICATION "Unknown"
set FILEDATE "02-09-2010 10:31:54.314"
set SYMBOLICNAME "policy_Test"
proc updatePolicy {_sPolicy _lsArgs}  {
re...

_Original issue: http://code.google.com/p/mxupdate/issues/detail?id=98_

**Comment by moxter** [comment]
To loose no productive data, rename / delete of states will be not supported from MxUdpate. This must be done manually with a script.
